/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "error-container": "#ffdad6",
              "on-tertiary-container": "#f6feff",
              "tertiary": "#4b6062",
              "inverse-surface": "#2d3133",
              "surface-dim": "#d8dadd",
              "on-primary-fixed-variant": "#004e60",
              "surface": "#f7f9fc",
              "on-surface-variant": "#414755",
              "inverse-on-surface": "#eff1f4",
              "inverse-primary": "#47d6ff",
              "on-primary": "#ffffff",
              "secondary-container": "#cfe1fb",
              "secondary": "#4f6076",
              "on-surface": "#191c1e",
              "on-secondary-fixed": "#0a1c30",
              "secondary-fixed": "#d2e4fe",
              "surface-variant": "#e0e3e6",
              "primary-container": "#007f9b",
              "on-secondary-container": "#53647a",
              "surface-container-low": "#f2f4f7",
              "on-error-container": "#93000a",
              "on-tertiary": "#ffffff",
              "outline": "#717786",
              "tertiary-container": "#63787b",
              "on-primary-container": "#fafdff",
              "surface-bright": "#f7f9fc",
              "error": "#ba1a1a",
              "on-tertiary-fixed-variant": "#364a4d",
              "on-error": "#ffffff",
              "secondary-fixed-dim": "#b6c8e2",
              "tertiary-fixed-dim": "#b4cbce",
              "surface-container-high": "#e6e8eb",
              "outline-variant": "#c1c6d7",
              "on-background": "#191c1e",
              "surface-tint": "#00677f",
              "surface-container": "#eceef1",
              "on-tertiary-fixed": "#091f21",
              "surface-container-lowest": "#ffffff",
              "background": "#f7f9fc",
              "primary": "#00657b",
              "on-primary-fixed": "#001f28",
              "on-secondary": "#ffffff",
              "primary-fixed-dim": "#47d6ff",
              "tertiary-fixed": "#d0e7ea",
              "primary-fixed": "#b6ebff",
              "on-secondary-fixed-variant": "#37485d",
              "surface-container-highest": "#e0e3e6"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "2xl": "1rem",
              "3xl": "1.5rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
